name: Pull Request Checks

on:
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    strategy:
      matrix:
        php: ['8.2']
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer
          coverage: xdebug

      - name: Install dependencies
        run: composer update -W --no-progress

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Run Laravel Pint (check mode)
        run: ./vendor/bin/pint --test

      - name: Run Pest Tests
        run: ./vendor/bin/pest --ci
